### 상품 등록
POST http://localhost:8083/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 리미티드 에디션"
}
### 상품 아이템 추가
POST http://localhost:8083/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8


{
  "productId": 1,
  "count": 1,
  "name": "나익기",
  "price": 100000
}

### 상품 수정
PUT http://localhost:8083/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "270",
      "price": 120000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스"
}
### 상품 아이템 수정
PUT http://localhost:8083/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8


{
  "id": 1,
  "productId": 1,
  "count": 1,
  "name": "나익기",
  "price": 100000
}

### 상품 삭제
DELETE http://localhost:8083/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8

### 상품 아이템 삭제
DELETE http://localhost:8083/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8

### 상품 검색
GET http://localhost:8083/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8083/search/product/detail?productId=1
Content-Type: application/json

### 장바구니 추가
POST http://localhost:8083/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 리미티드 에디션",
  "sellerId": 1
}