### 상품 등록
POST http://localhost:8083/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8


{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스"
}
### 상품 아이템 추가
POST http://localhost:8083/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJMR3pqdWEyK1JDWDFTR0t0dlJGeFJwUnlvd3VGSG9ZOXpVZk1DUUtUMWVrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwNDQxMDM3LCJleHAiOjE2ODA1Mjc0Mzd9.MIyEDJphAfpYc3zjI-X3qvU3ihDBTlCUhl4ISubgEa8


{
  "productId": 1,
  "count": 1,
  "name": "나익기",
  "price": 100000
}
